services:
  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: always
    environment:
      - FLOWISE_USERNAME=bip
      - FLOWISE_PASSWORD=Production_123
      - PORT=3000
      - NODE_VERSION=22
      - APIKEY_PATH=/opt/render/.flowise
      - DATABASE_PATH=/opt/render/.flowise
      - LOG_PATH=/opt/render/.flowise/logs
      - SECRETKEY_PATH=/opt/render/.flowise
    volumes:
      - ./data/flowise:/opt/render/.flowise
    networks:
      - makuro-network
    depends_on:
      - flowise-qdrant
      - flowise-postgres
      - flowise-redis
  flowise-qdrant:
    image: qdrant/qdrant:latest
    container_name: flowise-qdrant
    restart: unless-stopped
    volumes:
      - ./data/qdrant:/qdrant/storage
    networks:
      - makuro-network

  flowise-postgres:
    image: postgres:16
    container_name: flowise-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: bip
      POSTGRES_PASSWORD: Production_123
      POSTGRES_DB: jenna
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - makuro-network

  flowise-redis:
    image: redis:7.2
    container_name: flowise-redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./data/redis:/data
    networks:
      - makuro-network

networks:
  makuro-network:
    external: true
