services:
  db:
    image: mariadb:10.11
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Production_123
      - MYSQL_DATABASE=seafile_db
      - MYSQL_USER=bip
      - MYSQL_PASSWORD=Production_123
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always

  memcached:
    image: memcached:alpine
    container_name: seafile-memcached
    restart: always

  seafile:
    image: seafileltd/seafile-mc:latest
    container_name: seafile
    ports:
      - "8800:80"  # expose ke port 8800 untuk akses di Mac
    volumes:
      - ./seafile:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=Production_123
      - DB_NAME=seafile_db
      - DB_USER=bip
      - DB_PASSWORD=Production_123
      - SEAFILE_ADMIN_EMAIL=bip@wibudev.com
      - SEAFILE_ADMIN_PASSWORD=Production_123
      - SEAFILE_SERVER_NAME=seafile.wibudev.com
      - SEAFILE_USE_HTTPS=true
      - SEAFILE_SERVER_LETSENCRYPT=false
      - TZ=Asia/Jakarta
      - SERVICE_URL=https://seafile.wibudev.com
    depends_on:
      - db
      - memcached
    restart: always


#penanganann error  403
# Enter the seafile container
# `docker exec -it seafile bash`

# Edit the seahub_settings.py file
# `vi /opt/seafile/conf/seahub_settings.py`

# tambahkan
#ALLOWED_HOSTS = ['office2-seafile.wibudev.com', 'localhost', '127.0.0.1']
#CSRF_TRUSTED_ORIGINS = ['https://office2-seafile.wibudev.com']
