name: Update README TOC

on:
  push:
    branches:
      - master
    paths:
      - "**/*.md"
      - ".github/workflows/toc.yml"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  toc:
    name: Generate TOC
    runs-on: ubuntu-latest

    steps:
      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "."
          MAX_HEADER_LEVEL: 3
          TOC_TITLE: "## Table of Contents"
          COMMIT_MESSAGE: "docs: update README TOC"
