name: Update README TOC

on:
  push:
    branches:
      - master

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generateTOC:
    name: Generate TOC
    runs-on: ubuntu-latest

    steps:
      - name: Generate TOC
        uses: technote-space/toc-generator@v4
        with:
          TARGET_PATHS: "."
          MAX_HEADER_LEVEL: 3
          OPENING_COMMENT: "<!-- toc"
          CLOSING_COMMENT: "<!-- tocstop"
          COMMIT_MESSAGE: "docs: update README TOC"
          GITHUB_TOKEN: ${{ github.token }}
